
workflows:
  android-debug-apk:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & get
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  android-release-aab:
    name: Android Release AAB (unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get
      - name: Build app bundle
        script: flutter build appbundle --release --no-shrink
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

  ios-debug-ipa:
    name: iOS Debug (no codesign)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS (debug)
        script: |
          flutter build ios --debug --no-codesign || true
    artifacts:
      - build/ios/iphoneos/**/*.app
